export default colors = [
    { bg:"#8789C0", co:"white" },
    { bg: "#769FB6", co:"white" },
    { bg: "#188FA7", co:"white" },
    { bg: "#9DBBAE", co:"white" }, 
    { bg: "#D5D6AA", co:"white" }, 
    { bg: "#BF1363", co:"white" }, 
    { bg: "#0E79B2", co:"white" }, 
    { bg: "#B8E0D2", co:"white" },
    { bg: "#754F5B", co:"white" }, 
    { bg: "#E6DBD0", co:"white" }, 
    { bg: "#71B340", co:"white" }, 
    { bg: "#235016", co:"white" }, 
    { bg: "#FF74D4", co:"white" }, 
    { bg: "#D68C45", co:"white" }, 
    { bg: "#95B8D1", co:"white" }, 
    { bg: "#EA526F", co:"white" }, 
    { bg: "#89937C", co:"white" }, 
    { bg: "#715B64", co:"white" },
    { bg: "#82A7A6", co: "white" },
    { bg: "#A23E48", co: "white" },
    { bg: "#6C8EAD", co: "white" },
    { bg: "#AFD5AA", co: "white" },
    { bg: "#F0F2EF", co: "black" },
    { bg: "#A69F98", co: "black" },
    { bg: "#634B66", co: "white" },
    { bg: "#BBCBCB", co: "white" },
    { bg: "#E5FFDE", co: "black" },
    { bg: "#0C6291", co: "white" },
    { bg: "#7E1946", co: "white" },
    { bg: "#A63446", co: "white" },
    { bg: "#A7C957", co: "black" },
    { bg: "#386641", co: "white" },
    { bg: "#6A994E", co: "white" },
    { bg: "#721817", co: "white" },
    { bg: "#BC4749", co: "white" },
    { bg: "#F2E8CF", co: "black" },
    { bg: "#F7996E", co: "black" },
    { bg: "#FFAF87", co: "black" },
    { bg: "#F7996E", co: "black" },
    { bg: "#4C4C9D", co: "white" },
    { bg: "#712F79", co: "white" },
    { bg: "#C89FA3", co: "black" },
    { bg: "#DBB3B1", co: "black" },
    { bg: "#8FD5A6", co: "black" },
    { bg: "#7F557D", co: "white" },
    { bg: "#83B5D1", co: "black" },
    { bg: "#59594A", co: "white" },
    { bg: "#CDE7B0", co: "black" },
    { bg: "#BE6E46", co: "white" },
    { bg: "#241023", co: "white" },
    { bg: "#B8B8FF", co: "black" },
    { bg: "#FFD8BE", co: "black" },
    { bg: "#2F2F2F", co: "white" },
    { bg: "#F8F7FF", co: "black" }
]
